version: 2
updates:
  - package-ecosystem: uv
    directory: /source/core
    schedule:
      interval: weekly
      time: 08:00
      timezone: Europe/Copenhagen
    assignees:
      - "awha86"
      - "Gizmooa"
      - "HenrikSommer"
      - "jonasdmoeller"
      - "prtandrup"
      - "ShaBloze"
      - "x-platformcoder"
    commit-message:
      prefix: "Volt/Chore: "

  - package-ecosystem: nuget
    directory: /source/dotnet
    schedule:
      interval: weekly
      time: 08:00
      timezone: Europe/Copenhagen
    assignees:
      - "awha86"
      - "Gizmooa"
      - "HenrikSommer"
      - "jonasdmoeller"
      - "prtandrup"
      - "ShaBloze"
      - "x-platformcoder"
    commit-message:
      prefix: "Volt/Chore: "

  - package-ecosystem: uv
    directory: /source/geh_calculated_measurements
    schedule:
      interval: weekly
      time: 08:00
      timezone: Europe/Copenhagen
    assignees:
      - "BjarkeMeier"
    commit-message:
      prefix: "Mandalorian/Chore: "
