version: 2
updates:
  - package-ecosystem: uv
    directory: /source/core
    schedule:
      interval: weekly
      time: 08:00
      timezone: Europe/Copenhagen
    assignees:
      - "@Volt"
    commit-message:
      prefix: "[Volt]"

  - package-ecosystem: nuget
    directory: /source/dotnet
    schedule:
      interval: weekly
      time: 08:00
      timezone: Europe/Copenhagen
    assignees:
      - "@Volt"
    commit-message:
      prefix: "[Volt]"

  - package-ecosystem: uv
    directory: /source/geh_calculated_measurements
    schedule:
      interval: weekly
      time: 08:00
      timezone: Europe/Copenhagen
    assignees:
      - "@Mandalorian"
    commit-message:
      prefix: "[Mandalorian]"
