UPDATE {silver_database}.{silver_measurements_table}
SET metering_point_type = CASE
        WHEN metering_point_type == 'E17' THEN 'consumption'
        WHEN metering_point_type == 'E18' THEN 'production'
        WHEN metering_point_type == 'E20' THEN 'exchange'
        WHEN metering_point_type == 'D01' THEN 've_production'
        WHEN metering_point_type == 'D02' THEN 'analysis'
        WHEN metering_point_type == 'D03' THEN 'not_used'
        WHEN metering_point_type == 'D04' THEN 'surplus_production_group_6'
        WHEN metering_point_type == 'D05' THEN 'net_production'
        WHEN metering_point_type == 'D06' THEN 'supply_to_grid'
        WHEN metering_point_type == 'D07' THEN 'consumption_from_grid'
        WHEN metering_point_type == 'D08' THEN 'wholesale_services_information'
        WHEN metering_point_type == 'D09' THEN 'own_production'
        WHEN metering_point_type == 'D10' THEN 'net_from_grid'
        WHEN metering_point_type == 'D11' THEN 'net_to_grid'
        WHEN metering_point_type == 'D12' THEN 'total_consumption'
        WHEN metering_point_type == 'D13' THEN 'net_loss_correction'
        WHEN metering_point_type == 'D14' THEN 'electrical_heating'
        WHEN metering_point_type == 'D15' THEN 'net_consumption'
        WHEN metering_point_type == 'D17' THEN 'other_consumption'
        WHEN metering_point_type == 'D18' THEN 'other_production'
        WHEN metering_point_type == 'D19' THEN 'capacity_settlement'
        WHEN metering_point_type == 'D20' THEN 'exchange_reactive_energy'
        WHEN metering_point_type == 'D21' THEN 'collective_net_production'
        WHEN metering_point_type == 'D22' THEN 'collective_net_consumption'
        WHEN metering_point_type == 'D99' THEN 'internal_use'
        ELSE metering_point_type
    END
GO

UPDATE {gold_database}.{gold_measurements}
SET metering_point_type = CASE
        WHEN metering_point_type == 'E17' THEN 'consumption'
        WHEN metering_point_type == 'E18' THEN 'production'
        WHEN metering_point_type == 'E20' THEN 'exchange'
        WHEN metering_point_type == 'D01' THEN 've_production'
        WHEN metering_point_type == 'D02' THEN 'analysis'
        WHEN metering_point_type == 'D03' THEN 'not_used'
        WHEN metering_point_type == 'D04' THEN 'surplus_production_group_6'
        WHEN metering_point_type == 'D05' THEN 'net_production'
        WHEN metering_point_type == 'D06' THEN 'supply_to_grid'
        WHEN metering_point_type == 'D07' THEN 'consumption_from_grid'
        WHEN metering_point_type == 'D08' THEN 'wholesale_services_information'
        WHEN metering_point_type == 'D09' THEN 'own_production'
        WHEN metering_point_type == 'D10' THEN 'net_from_grid'
        WHEN metering_point_type == 'D11' THEN 'net_to_grid'
        WHEN metering_point_type == 'D12' THEN 'total_consumption'
        WHEN metering_point_type == 'D13' THEN 'net_loss_correction'
        WHEN metering_point_type == 'D14' THEN 'electrical_heating'
        WHEN metering_point_type == 'D15' THEN 'net_consumption'
        WHEN metering_point_type == 'D17' THEN 'other_consumption'
        WHEN metering_point_type == 'D18' THEN 'other_production'
        WHEN metering_point_type == 'D19' THEN 'capacity_settlement'
        WHEN metering_point_type == 'D20' THEN 'exchange_reactive_energy'
        WHEN metering_point_type == 'D21' THEN 'collective_net_production'
        WHEN metering_point_type == 'D22' THEN 'collective_net_consumption'
        WHEN metering_point_type == 'D99' THEN 'internal_use'
        ELSE metering_point_type
    END
