class GoldMeasurementsColumnNames:
    metering_point_id = "metering_point_id"
    orchestration_type = "orchestration_type"
    orchestration_instance_id = "orchestration_instance_id"
    observation_time = "observation_time"
    quantity = "quantity"
    quality = "quality"
    metering_point_type = "metering_point_type"
    unit = "unit"
    resolution = "resolution"
    transaction_id = "transaction_id"
    transaction_creation_datetime = "transaction_creation_datetime"
    is_cancelled = "is_cancelled"
    created = "created"
    modified = "modified"
