class ColumnNames:
    has_electrical_heating = "has_electrical_heating"
    metering_point_id = "metering_point_id"
    metering_point_sub_type = "metering_point_sub_type"
    metering_point_type = "metering_point_type"
    net_settlement_group = "net_settlement_group"
    parent_metering_point_id = "parent_metering_point_id"
    period_from_date = "period_from_date"
    period_to_date = "period_to_date"
    resolution = "resolution"
    settlement_month = "settlement_month"
