class SubmittedTransactionsQuarantinedColumnNames:
    orchestration_type = "orchestration_type"
    orchestration_instance_id = "orchestration_instance_id"
    metering_point_id = "metering_point_id"
    transaction_id = "transaction_id"
    transaction_creation_datetime = "transaction_creation_datetime"
    metering_point_type = "metering_point_type"
    unit = "unit"
    resolution = "resolution"
    start_datetime = "start_datetime"
    end_datetime = "end_datetime"
    points = "points"
    is_cancelled = "is_cancelled"
    created = "created"
    validate_orchestration_type_enum = "validate_orchestration_type_enum"
    validate_quality_enum = "validate_quality_enum"
    validate_metering_point_type_enum = "validate_metering_point_type_enum"
    validate_unit_enum = "validate_unit_enum"
    validate_resolution_enum = "validate_resolution_enum"

    class Points:
        position = "position"
        quantity = "quantity"
        quality = "quality"
