class SubmittedTransactionsQuarantinedColumnNames:
    orchestration_type = "orchestration_type"
    orchestration_instance_id = "orchestration_instance_id"
    metering_point_id = "metering_point_id"
    transaction_id = "transaction_id"
    transaction_creation_datetime = "transaction_creation_datetime"
    metering_point_type = "metering_point_type"
    unit = "unit"
    resolution = "resolution"
    start_datetime = "start_datetime"
    end_datetime = "end_datetime"
    points = "points"
    created = "created"
    validate_orchestration_type = "validate_orchestration_type"
    validate_quality = "validate_quality"
    validate_metering_point_type = "validate_metering_point_type"
    validate_unit = "validate_unit"
    validate_resolution = "validate_resolution"

    class Points:
        position = "position"
        quantity = "quantity"
        quality = "quality"
