class ColumnNames:
    calculation_id = "calculation_id"
    coupled_date = "coupled_date"
    execution_start_datetime = "execution_start_datetime"
    execution_stop_datetime = "execution_stop_datetime"
    metering_point_id = "metering_point_id"
    metering_point_type = "metering_point_type"
    net_settlement_group = "net_settlement_group"
    observation_time = "observation_time"
    orchestration_instance_id = "orchestration_instance_id"
    parent_metering_point_id = "parent_metering_point_id"
    period_from_date = "period_from_date"
    period_to_date = "period_to_date"
    quantity = "quantity"
    uncoupled_date = "uncoupled_date"
