services:
    workspace:
        image: workspace:latest
        build:
            args:
                SPARK_VERSION: 3.5.4
                UBUNTU_VERSION: '24.04'
                UV_VERSION: 0.5.15
            context: ..
            dockerfile: .docker/Dockerfile
        command: sleep infinity
        volumes:
        - ..:/workspace:cached
    bronze:
        image: bronze:latest
        build:
            args:
                SPARK_VERSION: 3.5.4
                UBUNTU_VERSION: '24.04'
                UV_VERSION: 0.5.15
            context: ..
            dockerfile: .docker/Dockerfile
        command: sleep infinity
        volumes:
        - ..:/workspace:cached
    silver:
        image: silver:latest
        build:
            args:
                SPARK_VERSION: 3.5.4
                UBUNTU_VERSION: '24.04'
                UV_VERSION: 0.5.15
            context: ..
            dockerfile: .docker/Dockerfile
        command: sleep infinity
        volumes:
        - ..:/workspace:cached
    gold:
        image: gold:latest
        build:
            args:
                SPARK_VERSION: 3.5.4
                UBUNTU_VERSION: '24.04'
                UV_VERSION: 0.5.15
            context: ..
            dockerfile: .docker/Dockerfile
        command: sleep infinity
        volumes:
        - ..:/workspace:cached
    electrical_heating:
        image: electrical_heating:latest
        build:
            args:
                SPARK_VERSION: 3.5.4
                UBUNTU_VERSION: '24.04'
                UV_VERSION: 0.5.15
            context: ..
            dockerfile: .docker/Dockerfile
        command: sleep infinity
        volumes:
        - ..:/workspace:cached
    capacity_settlement:
        image: capacity_settlement:latest
        build:
            args:
                SPARK_VERSION: 3.5.4
                UBUNTU_VERSION: '24.04'
                UV_VERSION: 0.5.15
            context: ..
            dockerfile: .docker/Dockerfile
        command: sleep infinity
        volumes:
        - ..:/workspace:cached
    calculated_measurements:
        image: calculated_measurements:latest
        build:
            args:
                SPARK_VERSION: 3.5.4
                UBUNTU_VERSION: '24.04'
                UV_VERSION: 0.5.15
            context: ..
            dockerfile: .docker/Dockerfile
        command: sleep infinity
        volumes:
        - ..:/workspace:cached