class ContractColumnNames:
    """Column names used in the dataframes."""

    coupled_date = "coupled_date"
    child_metering_point_id = "child_metering_point_id"
    child_period_from_date = "child_period_from_date"
    child_period_to_date = "child_period_to_date"
    date = "date"
    has_electrical_heating = "has_electrical_heating"
    metering_point_id = "metering_point_id"
    metering_point_sub_type = "metering_point_sub_type"
    metering_point_type = "metering_point_type"
    move_in = "move_in"
    net_settlement_group = "net_settlement_group"
    observation_time = "observation_time"
    orchestration_instance_id = "orchestration_instance_id"
    orchestration_type = "orchestration_type"
    parent_metering_point_id = "parent_metering_point_id"
    period_from_date = "period_from_date"
    period_to_date = "period_to_date"
    quantity = "quantity"
    settlement_month = "settlement_month"
    transaction_creation_datetime = "transaction_creation_datetime"
    transaction_id = "transaction_id"
    uncoupled_date = "uncoupled_date"
