class GoldMeasurementsColumnNames:
    metering_point_id = "metering_point_id"
    observation_time = "observation_time"
    quantity = "quantity"
    quality = "quality"
    metering_point_type = "metering_point_type"
    transaction_id = "transaction_id"
    transaction_creation_datetime = "transaction_creation_datetime"
    created = "created"
    modified = "modified"
