name: CI dotnet

on:
  workflow_call: {}

jobs:
  dotnet_ci_build:
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-build-prerelease.yml@v14
    with:
      solution_file_path: source/Measurements.sln

  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        tests_filter_expression:
          - name: Measurements
            path: \source\Measurements\Measurements.UnitTests\bin\Release\net8.0\Energinet.DataHub.Measurements.UnitTests.dll
          - name: MeasurementsApi
            path: \source\Measurements\MeasurementsApi.UnitTests\bin\Release\net8.0\Energinet.DataHub.Measurements.MeasurementsApi.UnitTests.dll
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-postbuild-test.yml@v14
    with:
      download_attempt_limit: 30
      azure_functions_core_tools_version: 4.0.5413
      # Matrix parameters
      job_name: Unit Tests ${{ matrix.tests_filter_expression.name }}
      tests_dll_file_path: ${{ matrix.tests_filter_expression.paths }}

  integration_tests:
    strategy:
      fail-fast: false
      matrix:
        tests_filter_expression:
          - name: Measurements
            path: \source\Measurements\Measurements.IntegrationTests\bin\Release\net8.0\Energinet.DataHub.Measurements.IntegrationTests.dll
          - name: MeasurementsApi
            path: \source\Measurements\MeasurementsApi.IntegrationTests\bin\Release\net8.0\Energinet.DataHub.Measurements.MeasurementsApi.IntegrationTests.dll
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-postbuild-test.yml@v14
    with:
      download_attempt_limit: 30
      azure_functions_core_tools_version: 4.0.5413
      # Matrix parameters
      job_name: Integration Tests ${{ matrix.tests_filter_expression.name }}
      tests_dll_file_path: ${{ matrix.tests_filter_expression.paths }}
