name: Detect changes

# DESCRIPTION:
# This workflow will determine which categories of jobs should be executed,
# based on detected changes.

on:
  workflow_call:
    outputs:
      dotnet:
        value: ${{ jobs.changes.outputs.dotnet }}
      packages:
        value: ${{ jobs.changes.outputs.packages }}
      measurements:
        value: ${{ jobs.changes.outputs.measurements }}

jobs:
  changes:
    name: Determine relevant jobs
    runs-on: ubuntu-latest
    outputs:
      dotnet: ${{ steps.filter.outputs.dotnet }}
      nuget-packages: ${{ steps.filter.outputs.nuget-packages }}
      measurements: ${{ steps.filter.outputs.measurements }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dotnet:
              - '.github/workflows/cd.yml'
              - '.github/workflows/ci-dotnet.yml'
              - 'source/dotnet/**'
            nuget-packages:
              - 'docs/Measurements.Client/**'
              - 'source/dotnet/Measurements.Client*/**'
              - 'source/dotnet/Measurements.Abstractions*/**'
              - '.github/workflows/measurements-client-bundle-publish.yml'
            measurements:
              - '.github/workflows/ci-orchestrator.yml'
              - 'source/geh_calculated_measurements/**'
